// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeDeviceAuthRequest = `-- name: CompleteDeviceAuthRequest :one
WITH completed_request AS (
    UPDATE device_auth_requests
    SET student_id = $3,
        status = 'approved'
    WHERE device_code = $1
      AND oauth_state = $2
      AND status = 'pending'
      AND expires_at > NOW()
    RETURNING public_key, student_id
),
upsert_user AS (
    INSERT INTO users (student_id)
    SELECT $3
    FROM completed_request
    ON CONFLICT (student_id) DO UPDATE
        SET student_id = EXCLUDED.student_id
    RETURNING id, student_id
),
inserted_key AS (
    INSERT INTO user_keys (user_id, public_key, fingerprint, device_name)
    SELECT upsert_user.id, completed_request.public_key, $4, $5
    FROM upsert_user, completed_request
    RETURNING id
)
SELECT upsert_user.id AS user_id,
       inserted_key.id AS user_key_id,
       upsert_user.student_id
FROM upsert_user, inserted_key
`

type CompleteDeviceAuthRequestParams struct {
	DeviceCode  string      `json:"device_code"`
	OauthState  pgtype.Text `json:"oauth_state"`
	StudentID   pgtype.Text `json:"student_id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
	DeviceName  string      `json:"device_name"`
}

type CompleteDeviceAuthRequestRow struct {
	UserID    int64  `json:"user_id"`
	UserKeyID int64  `json:"user_key_id"`
	StudentID string `json:"student_id"`
}

func (q *Queries) CompleteDeviceAuthRequest(ctx context.Context, arg CompleteDeviceAuthRequestParams) (CompleteDeviceAuthRequestRow, error) {
	row := q.db.QueryRow(ctx, completeDeviceAuthRequest,
		arg.DeviceCode,
		arg.OauthState,
		arg.StudentID,
		arg.Fingerprint,
		arg.DeviceName,
	)
	var i CompleteDeviceAuthRequestRow
	err := row.Scan(&i.UserID, &i.UserKeyID, &i.StudentID)
	return i, err
}

const createDeviceAuthRequest = `-- name: CreateDeviceAuthRequest :one
INSERT INTO device_auth_requests (device_code, user_code, public_key, device_name, student_id, oauth_state, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, device_code, user_code, public_key, device_name, student_id, oauth_state, status, expires_at, created_at
`

type CreateDeviceAuthRequestParams struct {
	DeviceCode string             `json:"device_code"`
	UserCode   string             `json:"user_code"`
	PublicKey  string             `json:"public_key"`
	DeviceName string             `json:"device_name"`
	StudentID  pgtype.Text        `json:"student_id"`
	OauthState pgtype.Text        `json:"oauth_state"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDeviceAuthRequest(ctx context.Context, arg CreateDeviceAuthRequestParams) (DeviceAuthRequests, error) {
	row := q.db.QueryRow(ctx, createDeviceAuthRequest,
		arg.DeviceCode,
		arg.UserCode,
		arg.PublicKey,
		arg.DeviceName,
		arg.StudentID,
		arg.OauthState,
		arg.Status,
		arg.ExpiresAt,
	)
	var i DeviceAuthRequests
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.PublicKey,
		&i.DeviceName,
		&i.StudentID,
		&i.OauthState,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (student_id)
VALUES ($1)
RETURNING id, student_id, created_at
`

func (q *Queries) CreateUser(ctx context.Context, studentID string) (Users, error) {
	row := q.db.QueryRow(ctx, createUser, studentID)
	var i Users
	err := row.Scan(&i.ID, &i.StudentID, &i.CreatedAt)
	return i, err
}

const createUserKey = `-- name: CreateUserKey :one
INSERT INTO user_keys (user_id, public_key, fingerprint, device_name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, public_key, device_name, created_at, revoked_at, fingerprint
`

type CreateUserKeyParams struct {
	UserID      int64       `json:"user_id"`
	PublicKey   string      `json:"public_key"`
	Fingerprint pgtype.Text `json:"fingerprint"`
	DeviceName  string      `json:"device_name"`
}

func (q *Queries) CreateUserKey(ctx context.Context, arg CreateUserKeyParams) (UserKeys, error) {
	row := q.db.QueryRow(ctx, createUserKey,
		arg.UserID,
		arg.PublicKey,
		arg.Fingerprint,
		arg.DeviceName,
	)
	var i UserKeys
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Fingerprint,
	)
	return i, err
}

const deleteUserKey = `-- name: DeleteUserKey :exec
UPDATE user_keys
SET revoked_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type DeleteUserKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserKey(ctx context.Context, arg DeleteUserKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserKey, arg.ID, arg.UserID)
	return err
}

const expireDeviceAuthRequests = `-- name: ExpireDeviceAuthRequests :exec
UPDATE device_auth_requests
SET status = 'expired'
WHERE status = 'pending'
  AND expires_at < NOW()
`

func (q *Queries) ExpireDeviceAuthRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireDeviceAuthRequests)
	return err
}

const getDeviceAuthRequestByDeviceCode = `-- name: GetDeviceAuthRequestByDeviceCode :one
SELECT id, device_code, user_code, public_key, device_name, student_id, oauth_state, status, expires_at, created_at
FROM device_auth_requests
WHERE device_code = $1
LIMIT 1
`

func (q *Queries) GetDeviceAuthRequestByDeviceCode(ctx context.Context, deviceCode string) (DeviceAuthRequests, error) {
	row := q.db.QueryRow(ctx, getDeviceAuthRequestByDeviceCode, deviceCode)
	var i DeviceAuthRequests
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.PublicKey,
		&i.DeviceName,
		&i.StudentID,
		&i.OauthState,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeviceAuthRequestByOAuthState = `-- name: GetPendingDeviceAuthRequestByOAuthState :one
SELECT id, device_code, user_code, public_key, device_name, student_id, oauth_state, status, expires_at, created_at
FROM device_auth_requests
WHERE oauth_state = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingDeviceAuthRequestByOAuthState(ctx context.Context, oauthState pgtype.Text) (DeviceAuthRequests, error) {
	row := q.db.QueryRow(ctx, getPendingDeviceAuthRequestByOAuthState, oauthState)
	var i DeviceAuthRequests
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.PublicKey,
		&i.DeviceName,
		&i.StudentID,
		&i.OauthState,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeviceAuthRequestByUserCode = `-- name: GetPendingDeviceAuthRequestByUserCode :one
SELECT id, device_code, user_code, public_key, device_name, student_id, oauth_state, status, expires_at, created_at
FROM device_auth_requests
WHERE user_code = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingDeviceAuthRequestByUserCode(ctx context.Context, userCode string) (DeviceAuthRequests, error) {
	row := q.db.QueryRow(ctx, getPendingDeviceAuthRequestByUserCode, userCode)
	var i DeviceAuthRequests
	err := row.Scan(
		&i.ID,
		&i.DeviceCode,
		&i.UserCode,
		&i.PublicKey,
		&i.DeviceName,
		&i.StudentID,
		&i.OauthState,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, student_id, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(&i.ID, &i.StudentID, &i.CreatedAt)
	return i, err
}

const getUserByStudentID = `-- name: GetUserByStudentID :one
SELECT id, student_id, created_at
FROM users
WHERE student_id = $1
LIMIT 1
`

func (q *Queries) GetUserByStudentID(ctx context.Context, studentID string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByStudentID, studentID)
	var i Users
	err := row.Scan(&i.ID, &i.StudentID, &i.CreatedAt)
	return i, err
}

const getUserKeyByFingerprint = `-- name: GetUserKeyByFingerprint :one
SELECT id, user_id, public_key, device_name, created_at, revoked_at, fingerprint
FROM user_keys
WHERE fingerprint = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserKeyByFingerprint(ctx context.Context, fingerprint pgtype.Text) (UserKeys, error) {
	row := q.db.QueryRow(ctx, getUserKeyByFingerprint, fingerprint)
	var i UserKeys
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Fingerprint,
	)
	return i, err
}

const getUserKeyByID = `-- name: GetUserKeyByID :one
SELECT id, user_id, public_key, device_name, created_at, revoked_at, fingerprint
FROM user_keys
WHERE id = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserKeyByID(ctx context.Context, id int64) (UserKeys, error) {
	row := q.db.QueryRow(ctx, getUserKeyByID, id)
	var i UserKeys
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.DeviceName,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Fingerprint,
	)
	return i, err
}

const listActiveUserKeys = `-- name: ListActiveUserKeys :many
SELECT id, user_id, public_key, device_name, created_at, revoked_at, fingerprint
FROM user_keys
WHERE revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUserKeys(ctx context.Context) ([]UserKeys, error) {
	rows, err := q.db.Query(ctx, listActiveUserKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserKeys{}
	for rows.Next() {
		var i UserKeys
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.DeviceName,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserKeys = `-- name: ListUserKeys :many
SELECT id, user_id, public_key, device_name, created_at, revoked_at, fingerprint
FROM user_keys
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserKeys(ctx context.Context, userID int64) ([]UserKeys, error) {
	rows, err := q.db.Query(ctx, listUserKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserKeys{}
	for rows.Next() {
		var i UserKeys
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.DeviceName,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserKeyFingerprint = `-- name: UpdateUserKeyFingerprint :exec
UPDATE user_keys
SET fingerprint = $2
WHERE id = $1
  AND fingerprint IS NULL
`

type UpdateUserKeyFingerprintParams struct {
	ID          int64       `json:"id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) UpdateUserKeyFingerprint(ctx context.Context, arg UpdateUserKeyFingerprintParams) error {
	_, err := q.db.Exec(ctx, updateUserKeyFingerprint, arg.ID, arg.Fingerprint)
	return err
}
