// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bonus_quota.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const adjustBonusQuotaForLab = `-- name: AdjustBonusQuotaForLab :execrows
INSERT INTO user_lab_bonus_quota (user_id, lab_id, remaining, updated_at)
SELECT s.user_id, $1::text, GREATEST(0, $2::int), NOW()
FROM (SELECT DISTINCT user_id FROM submissions WHERE lab_id = $1::text) AS s
ON CONFLICT (user_id, lab_id)
DO UPDATE SET
    remaining = GREATEST(0, user_lab_bonus_quota.remaining + $2::int),
    updated_at = NOW()
`

type AdjustBonusQuotaForLabParams struct {
	LabID string `json:"lab_id"`
	Delta int32  `json:"delta"`
}

func (q *Queries) AdjustBonusQuotaForLab(ctx context.Context, arg AdjustBonusQuotaForLabParams) (int64, error) {
	result, err := q.db.Exec(ctx, adjustBonusQuotaForLab, arg.LabID, arg.Delta)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeBonusQuota = `-- name: ConsumeBonusQuota :one
UPDATE user_lab_bonus_quota
SET remaining = remaining - 1,
    updated_at = NOW()
WHERE user_id = $1
  AND lab_id = $2
  AND remaining > 0
RETURNING remaining
`

type ConsumeBonusQuotaParams struct {
	UserID int64  `json:"user_id"`
	LabID  string `json:"lab_id"`
}

func (q *Queries) ConsumeBonusQuota(ctx context.Context, arg ConsumeBonusQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, consumeBonusQuota, arg.UserID, arg.LabID)
	var remaining int32
	err := row.Scan(&remaining)
	return remaining, err
}

const countLabParticipants = `-- name: CountLabParticipants :one
SELECT COUNT(DISTINCT user_id)
FROM submissions
WHERE lab_id = $1
`

func (q *Queries) CountLabParticipants(ctx context.Context, labID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLabParticipants, labID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBonusQuota = `-- name: GetBonusQuota :one
SELECT remaining
FROM user_lab_bonus_quota
WHERE user_id = $1 AND lab_id = $2
`

type GetBonusQuotaParams struct {
	UserID int64  `json:"user_id"`
	LabID  string `json:"lab_id"`
}

func (q *Queries) GetBonusQuota(ctx context.Context, arg GetBonusQuotaParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBonusQuota, arg.UserID, arg.LabID)
	var remaining int32
	err := row.Scan(&remaining)
	return remaining, err
}

const refundBonusSubmission = `-- name: RefundBonusSubmission :execrows
WITH flipped AS (
    UPDATE submissions
    SET quota_state = 'free'
    WHERE id = $1 AND quota_state = 'bonus'
    RETURNING user_id, lab_id
)
UPDATE user_lab_bonus_quota ulbq
SET remaining = remaining + 1,
    updated_at = NOW()
FROM flipped
WHERE ulbq.user_id = flipped.user_id
  AND ulbq.lab_id = flipped.lab_id
`

func (q *Queries) RefundBonusSubmission(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, refundBonusSubmission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetBonusQuotaForLab = `-- name: ResetBonusQuotaForLab :execrows
UPDATE user_lab_bonus_quota
SET remaining = 0,
    updated_at = NOW()
WHERE lab_id = $1
  AND remaining > 0
`

func (q *Queries) ResetBonusQuotaForLab(ctx context.Context, labID string) (int64, error) {
	result, err := q.db.Exec(ctx, resetBonusQuotaForLab, labID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
