// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFinalGradesByLab = `-- name: DeleteFinalGradesByLab :execrows
DELETE FROM final_grades
WHERE lab_id = $1
`

func (q *Queries) DeleteFinalGradesByLab(ctx context.Context, labID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinalGradesByLab, labID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFinalGrade = `-- name: GetFinalGrade :one
SELECT lab_id, student_id, total, remark, published_at, updated_at, items
FROM final_grades
WHERE lab_id = $1
  AND student_id = $2
  AND published_at IS NOT NULL
  AND published_at <= NOW()
LIMIT 1
`

type GetFinalGradeParams struct {
	LabID     string `json:"lab_id"`
	StudentID string `json:"student_id"`
}

func (q *Queries) GetFinalGrade(ctx context.Context, arg GetFinalGradeParams) (FinalGrades, error) {
	row := q.db.QueryRow(ctx, getFinalGrade, arg.LabID, arg.StudentID)
	var i FinalGrades
	err := row.Scan(
		&i.LabID,
		&i.StudentID,
		&i.Total,
		&i.Remark,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.Items,
	)
	return i, err
}

const listPublishedFinalGradesByStudent = `-- name: ListPublishedFinalGradesByStudent :many
SELECT lab_id, student_id, total, remark, published_at, updated_at, items
FROM final_grades
WHERE student_id = $1
  AND published_at IS NOT NULL
  AND published_at <= NOW()
ORDER BY updated_at DESC
`

func (q *Queries) ListPublishedFinalGradesByStudent(ctx context.Context, studentID string) ([]FinalGrades, error) {
	rows, err := q.db.Query(ctx, listPublishedFinalGradesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinalGrades{}
	for rows.Next() {
		var i FinalGrades
		if err := rows.Scan(
			&i.LabID,
			&i.StudentID,
			&i.Total,
			&i.Remark,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishFinalGrades = `-- name: PublishFinalGrades :execrows
UPDATE final_grades
SET published_at = NOW(),
    updated_at = NOW()
WHERE lab_id = $1
  AND published_at IS NULL
`

func (q *Queries) PublishFinalGrades(ctx context.Context, labID string) (int64, error) {
	result, err := q.db.Exec(ctx, publishFinalGrades, labID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const summarizeFinalGrades = `-- name: SummarizeFinalGrades :one
SELECT
    COUNT(*)                   AS total,
    COUNT(published_at)        AS published,
    MAX(updated_at)::timestamptz AS last_updated
FROM final_grades
WHERE lab_id = $1
`

type SummarizeFinalGradesRow struct {
	Total       int64              `json:"total"`
	Published   int64              `json:"published"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
}

func (q *Queries) SummarizeFinalGrades(ctx context.Context, labID string) (SummarizeFinalGradesRow, error) {
	row := q.db.QueryRow(ctx, summarizeFinalGrades, labID)
	var i SummarizeFinalGradesRow
	err := row.Scan(&i.Total, &i.Published, &i.LastUpdated)
	return i, err
}

const upsertFinalGrade = `-- name: UpsertFinalGrade :one
INSERT INTO final_grades (
    lab_id, student_id, total, remark, items, updated_at
)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (lab_id, student_id) DO UPDATE SET
    total = EXCLUDED.total,
    remark = EXCLUDED.remark,
    items = EXCLUDED.items,
    updated_at = NOW()
RETURNING lab_id, student_id, total, remark, published_at, updated_at, items
`

type UpsertFinalGradeParams struct {
	LabID     string          `json:"lab_id"`
	StudentID string          `json:"student_id"`
	Total     pgtype.Text     `json:"total"`
	Remark    pgtype.Text     `json:"remark"`
	Items     json.RawMessage `json:"items"`
}

func (q *Queries) UpsertFinalGrade(ctx context.Context, arg UpsertFinalGradeParams) (FinalGrades, error) {
	row := q.db.QueryRow(ctx, upsertFinalGrade,
		arg.LabID,
		arg.StudentID,
		arg.Total,
		arg.Remark,
		arg.Items,
	)
	var i FinalGrades
	err := row.Scan(
		&i.LabID,
		&i.StudentID,
		&i.Total,
		&i.Remark,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.Items,
	)
	return i, err
}
