// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFinalGradesByLab = `-- name: DeleteFinalGradesByLab :execrows
DELETE FROM final_grades
WHERE lab_id = $1
`

func (q *Queries) DeleteFinalGradesByLab(ctx context.Context, labID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinalGradesByLab, labID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFinalGrade = `-- name: GetFinalGrade :one
SELECT lab_id, student_id, total, track, ratio, perf_score, percentile, board_score, remark, published_at, updated_at
FROM final_grades
WHERE lab_id = $1
  AND student_id = $2
  AND published_at IS NOT NULL
  AND published_at <= NOW()
LIMIT 1
`

type GetFinalGradeParams struct {
	LabID     string `json:"lab_id"`
	StudentID string `json:"student_id"`
}

func (q *Queries) GetFinalGrade(ctx context.Context, arg GetFinalGradeParams) (FinalGrades, error) {
	row := q.db.QueryRow(ctx, getFinalGrade, arg.LabID, arg.StudentID)
	var i FinalGrades
	err := row.Scan(
		&i.LabID,
		&i.StudentID,
		&i.Total,
		&i.Track,
		&i.Ratio,
		&i.PerfScore,
		&i.Percentile,
		&i.BoardScore,
		&i.Remark,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishFinalGrades = `-- name: PublishFinalGrades :execrows
UPDATE final_grades
SET published_at = NOW(),
    updated_at = NOW()
WHERE lab_id = $1
  AND published_at IS NULL
`

func (q *Queries) PublishFinalGrades(ctx context.Context, labID string) (int64, error) {
	result, err := q.db.Exec(ctx, publishFinalGrades, labID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFinalGrade = `-- name: UpsertFinalGrade :one
INSERT INTO final_grades (
    lab_id, student_id, total, track, ratio, perf_score, percentile, board_score, remark, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (lab_id, student_id) DO UPDATE SET
    total = EXCLUDED.total,
    track = EXCLUDED.track,
    ratio = EXCLUDED.ratio,
    perf_score = EXCLUDED.perf_score,
    percentile = EXCLUDED.percentile,
    board_score = EXCLUDED.board_score,
    remark = EXCLUDED.remark,
    updated_at = NOW()
RETURNING lab_id, student_id, total, track, ratio, perf_score, percentile, board_score, remark, published_at, updated_at
`

type UpsertFinalGradeParams struct {
	LabID      string        `json:"lab_id"`
	StudentID  string        `json:"student_id"`
	Total      float32       `json:"total"`
	Track      pgtype.Text   `json:"track"`
	Ratio      pgtype.Float4 `json:"ratio"`
	PerfScore  pgtype.Float4 `json:"perf_score"`
	Percentile pgtype.Float4 `json:"percentile"`
	BoardScore pgtype.Float4 `json:"board_score"`
	Remark     pgtype.Text   `json:"remark"`
}

func (q *Queries) UpsertFinalGrade(ctx context.Context, arg UpsertFinalGradeParams) (FinalGrades, error) {
	row := q.db.QueryRow(ctx, upsertFinalGrade,
		arg.LabID,
		arg.StudentID,
		arg.Total,
		arg.Track,
		arg.Ratio,
		arg.PerfScore,
		arg.Percentile,
		arg.BoardScore,
		arg.Remark,
	)
	var i FinalGrades
	err := row.Scan(
		&i.LabID,
		&i.StudentID,
		&i.Total,
		&i.Track,
		&i.Ratio,
		&i.PerfScore,
		&i.Percentile,
		&i.BoardScore,
		&i.Remark,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
