// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvaluationJob = `-- name: CreateEvaluationJob :one
INSERT INTO evaluation_jobs (submission_id)
VALUES ($1)
RETURNING id, submission_id, status, attempts, available_at, worker_id, last_error, started_at, finished_at, created_at, updated_at
`

func (q *Queries) CreateEvaluationJob(ctx context.Context, submissionID uuid.UUID) (EvaluationJobs, error) {
	row := q.db.QueryRow(ctx, createEvaluationJob, submissionID)
	var i EvaluationJobs
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.WorkerID,
		&i.LastError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextQueuedEvaluationJob = `-- name: GetNextQueuedEvaluationJob :one
SELECT id, submission_id, status, attempts, available_at, worker_id, last_error, started_at, finished_at, created_at, updated_at
FROM evaluation_jobs
WHERE status = 'queued' AND available_at <= NOW()
ORDER BY available_at, created_at
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetNextQueuedEvaluationJob(ctx context.Context) (EvaluationJobs, error) {
	row := q.db.QueryRow(ctx, getNextQueuedEvaluationJob)
	var i EvaluationJobs
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.WorkerID,
		&i.LastError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentEvaluationJobsByLab = `-- name: ListRecentEvaluationJobsByLab :many
SELECT
    ej.id,
    ej.submission_id,
    s.user_id,
    s.lab_id,
    ej.status,
    ej.attempts,
    ej.available_at,
    ej.worker_id,
    ej.last_error,
    ej.started_at,
    ej.finished_at,
    ej.created_at,
    ej.updated_at
FROM evaluation_jobs ej
JOIN submissions s ON s.id = ej.submission_id
WHERE s.lab_id = $1
ORDER BY ej.updated_at DESC, ej.created_at DESC
LIMIT $2
`

type ListRecentEvaluationJobsByLabParams struct {
	LabID string `json:"lab_id"`
	Limit int32  `json:"limit"`
}

type ListRecentEvaluationJobsByLabRow struct {
	ID           uuid.UUID          `json:"id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	UserID       int64              `json:"user_id"`
	LabID        string             `json:"lab_id"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	WorkerID     pgtype.Text        `json:"worker_id"`
	LastError    pgtype.Text        `json:"last_error"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRecentEvaluationJobsByLab(ctx context.Context, arg ListRecentEvaluationJobsByLabParams) ([]ListRecentEvaluationJobsByLabRow, error) {
	rows, err := q.db.Query(ctx, listRecentEvaluationJobsByLab, arg.LabID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentEvaluationJobsByLabRow{}
	for rows.Next() {
		var i ListRecentEvaluationJobsByLabRow
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.LabID,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.WorkerID,
			&i.LastError,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEvaluationJobDone = `-- name: MarkEvaluationJobDone :execrows
UPDATE evaluation_jobs
SET status = $2,
    last_error = $4,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'running'
  AND worker_id = $3
`

type MarkEvaluationJobDoneParams struct {
	ID        uuid.UUID   `json:"id"`
	Status    string      `json:"status"`
	WorkerID  pgtype.Text `json:"worker_id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEvaluationJobDone(ctx context.Context, arg MarkEvaluationJobDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEvaluationJobDone,
		arg.ID,
		arg.Status,
		arg.WorkerID,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEvaluationJobRunning = `-- name: MarkEvaluationJobRunning :exec
UPDATE evaluation_jobs
SET status = 'running',
    attempts = attempts + 1,
    worker_id = $2,
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkEvaluationJobRunningParams struct {
	ID       uuid.UUID   `json:"id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) MarkEvaluationJobRunning(ctx context.Context, arg MarkEvaluationJobRunningParams) error {
	_, err := q.db.Exec(ctx, markEvaluationJobRunning, arg.ID, arg.WorkerID)
	return err
}

const requeueEvaluationJob = `-- name: RequeueEvaluationJob :execrows
UPDATE evaluation_jobs
SET status = 'queued',
    available_at = $3,
    worker_id = NULL,
    started_at = NULL,
    finished_at = NULL,
    last_error = $4,
    updated_at = NOW()
WHERE id = $1
  AND status = 'running'
  AND worker_id = $2
`

type RequeueEvaluationJobParams struct {
	ID          uuid.UUID          `json:"id"`
	WorkerID    pgtype.Text        `json:"worker_id"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) RequeueEvaluationJob(ctx context.Context, arg RequeueEvaluationJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueEvaluationJob,
		arg.ID,
		arg.WorkerID,
		arg.AvailableAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
