// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labs.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createLab = `-- name: CreateLab :one
INSERT INTO labs (id, name, manifest, manifest_updated_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, name, manifest, manifest_updated_at, created_at
`

type CreateLabParams struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Manifest json.RawMessage `json:"manifest"`
}

func (q *Queries) CreateLab(ctx context.Context, arg CreateLabParams) (Labs, error) {
	row := q.db.QueryRow(ctx, createLab, arg.ID, arg.Name, arg.Manifest)
	var i Labs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manifest,
		&i.ManifestUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLab = `-- name: GetLab :one
SELECT id, name, manifest, manifest_updated_at, created_at
FROM labs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLab(ctx context.Context, id string) (Labs, error) {
	row := q.db.QueryRow(ctx, getLab, id)
	var i Labs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manifest,
		&i.ManifestUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLabs = `-- name: ListLabs :many
SELECT id, name, manifest, manifest_updated_at, created_at
FROM labs
ORDER BY created_at DESC
`

func (q *Queries) ListLabs(ctx context.Context) ([]Labs, error) {
	rows, err := q.db.Query(ctx, listLabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Labs{}
	for rows.Next() {
		var i Labs
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Manifest,
			&i.ManifestUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabManifest = `-- name: UpdateLabManifest :exec
UPDATE labs
SET name = $2,
    manifest = $3,
    manifest_updated_at = NOW()
WHERE id = $1
`

type UpdateLabManifestParams struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Manifest json.RawMessage `json:"manifest"`
}

func (q *Queries) UpdateLabManifest(ctx context.Context, arg UpdateLabManifestParams) error {
	_, err := q.db.Exec(ctx, updateLabManifest, arg.ID, arg.Name, arg.Manifest)
	return err
}
