// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLeaderboardEntry = `-- name: GetLeaderboardEntry :one
SELECT user_id, lab_id, submission_id, updated_at
FROM leaderboard
WHERE user_id = $1 AND lab_id = $2
LIMIT 1
`

type GetLeaderboardEntryParams struct {
	UserID int64  `json:"user_id"`
	LabID  string `json:"lab_id"`
}

func (q *Queries) GetLeaderboardEntry(ctx context.Context, arg GetLeaderboardEntryParams) (Leaderboard, error) {
	row := q.db.QueryRow(ctx, getLeaderboardEntry, arg.UserID, arg.LabID)
	var i Leaderboard
	err := row.Scan(
		&i.UserID,
		&i.LabID,
		&i.SubmissionID,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaderboardByLab = `-- name: ListLeaderboardByLab :many
SELECT user_id, lab_id, submission_id, updated_at
FROM leaderboard
WHERE lab_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListLeaderboardByLab(ctx context.Context, labID string) ([]Leaderboard, error) {
	rows, err := q.db.Query(ctx, listLeaderboardByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Leaderboard{}
	for rows.Next() {
		var i Leaderboard
		if err := rows.Scan(
			&i.UserID,
			&i.LabID,
			&i.SubmissionID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaderboardByLabAndMetricAsc = `-- name: ListLeaderboardByLabAndMetricAsc :many
SELECT
    lb.user_id,
    u.nickname,
    lb.lab_id,
    lb.submission_id,
    lb.updated_at,
    s.metric_id,
    s.value
FROM leaderboard lb
JOIN users u ON u.id = lb.user_id
JOIN scores s ON s.submission_id = lb.submission_id
WHERE lb.lab_id = $1 AND s.metric_id = $2
ORDER BY s.value ASC, lb.updated_at ASC
`

type ListLeaderboardByLabAndMetricAscParams struct {
	LabID    string `json:"lab_id"`
	MetricID string `json:"metric_id"`
}

type ListLeaderboardByLabAndMetricAscRow struct {
	UserID       int64              `json:"user_id"`
	Nickname     string             `json:"nickname"`
	LabID        string             `json:"lab_id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MetricID     string             `json:"metric_id"`
	Value        float32            `json:"value"`
}

func (q *Queries) ListLeaderboardByLabAndMetricAsc(ctx context.Context, arg ListLeaderboardByLabAndMetricAscParams) ([]ListLeaderboardByLabAndMetricAscRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboardByLabAndMetricAsc, arg.LabID, arg.MetricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardByLabAndMetricAscRow{}
	for rows.Next() {
		var i ListLeaderboardByLabAndMetricAscRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.LabID,
			&i.SubmissionID,
			&i.UpdatedAt,
			&i.MetricID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaderboardByLabAndMetricDesc = `-- name: ListLeaderboardByLabAndMetricDesc :many
SELECT
    lb.user_id,
    u.nickname,
    lb.lab_id,
    lb.submission_id,
    lb.updated_at,
    s.metric_id,
    s.value
FROM leaderboard lb
JOIN users u ON u.id = lb.user_id
JOIN scores s ON s.submission_id = lb.submission_id
WHERE lb.lab_id = $1 AND s.metric_id = $2
ORDER BY s.value DESC, lb.updated_at DESC
`

type ListLeaderboardByLabAndMetricDescParams struct {
	LabID    string `json:"lab_id"`
	MetricID string `json:"metric_id"`
}

type ListLeaderboardByLabAndMetricDescRow struct {
	UserID       int64              `json:"user_id"`
	Nickname     string             `json:"nickname"`
	LabID        string             `json:"lab_id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MetricID     string             `json:"metric_id"`
	Value        float32            `json:"value"`
}

func (q *Queries) ListLeaderboardByLabAndMetricDesc(ctx context.Context, arg ListLeaderboardByLabAndMetricDescParams) ([]ListLeaderboardByLabAndMetricDescRow, error) {
	rows, err := q.db.Query(ctx, listLeaderboardByLabAndMetricDesc, arg.LabID, arg.MetricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardByLabAndMetricDescRow{}
	for rows.Next() {
		var i ListLeaderboardByLabAndMetricDescRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.LabID,
			&i.SubmissionID,
			&i.UpdatedAt,
			&i.MetricID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScoresByLab = `-- name: ListScoresByLab :many
SELECT
    s.submission_id,
    s.metric_id,
    s.value
FROM leaderboard lb
JOIN scores s ON s.submission_id = lb.submission_id
WHERE lb.lab_id = $1
ORDER BY s.submission_id, s.metric_id
`

func (q *Queries) ListScoresByLab(ctx context.Context, labID string) ([]Scores, error) {
	rows, err := q.db.Query(ctx, listScoresByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scores{}
	for rows.Next() {
		var i Scores
		if err := rows.Scan(&i.SubmissionID, &i.MetricID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLeaderboardEntry = `-- name: UpsertLeaderboardEntry :one
INSERT INTO leaderboard (user_id, lab_id, submission_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, lab_id)
DO UPDATE SET submission_id = EXCLUDED.submission_id,
              updated_at = NOW()
RETURNING user_id, lab_id, submission_id, updated_at
`

type UpsertLeaderboardEntryParams struct {
	UserID       int64     `json:"user_id"`
	LabID        string    `json:"lab_id"`
	SubmissionID uuid.UUID `json:"submission_id"`
}

func (q *Queries) UpsertLeaderboardEntry(ctx context.Context, arg UpsertLeaderboardEntryParams) (Leaderboard, error) {
	row := q.db.QueryRow(ctx, upsertLeaderboardEntry, arg.UserID, arg.LabID, arg.SubmissionID)
	var i Leaderboard
	err := row.Scan(
		&i.UserID,
		&i.LabID,
		&i.SubmissionID,
		&i.UpdatedAt,
	)
	return i, err
}
