// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceAuthRequests struct {
	ID         int64              `json:"id"`
	DeviceCode string             `json:"device_code"`
	UserCode   string             `json:"user_code"`
	PublicKey  string             `json:"public_key"`
	StudentID  pgtype.Text        `json:"student_id"`
	OauthState pgtype.Text        `json:"oauth_state"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeviceName string             `json:"device_name"`
}

type EvaluationJobs struct {
	ID           uuid.UUID          `json:"id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	WorkerID     pgtype.Text        `json:"worker_id"`
	LastError    pgtype.Text        `json:"last_error"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LabProfiles struct {
	UserID   int64       `json:"user_id"`
	LabID    string      `json:"lab_id"`
	Nickname string      `json:"nickname"`
	Track    pgtype.Text `json:"track"`
}

type Labs struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Manifest          json.RawMessage    `json:"manifest"`
	ManifestUpdatedAt pgtype.Timestamptz `json:"manifest_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Leaderboard struct {
	UserID       int64              `json:"user_id"`
	LabID        string             `json:"lab_id"`
	SubmissionID uuid.UUID          `json:"submission_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Scores struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	MetricID     string    `json:"metric_id"`
	Value        float32   `json:"value"`
}

type Submissions struct {
	ID          uuid.UUID          `json:"id"`
	UserID      int64              `json:"user_id"`
	LabID       string             `json:"lab_id"`
	KeyID       int64              `json:"key_id"`
	ArtifactKey string             `json:"artifact_key"`
	ContentHash string             `json:"content_hash"`
	Status      string             `json:"status"`
	Verdict     pgtype.Text        `json:"verdict"`
	Message     pgtype.Text        `json:"message"`
	Detail      []byte             `json:"detail"`
	ImageDigest pgtype.Text        `json:"image_digest"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	QuotaState  string             `json:"quota_state"`
}

type UsedNonces struct {
	Nonce     string             `json:"nonce"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserKeys struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	PublicKey   string             `json:"public_key"`
	DeviceName  string             `json:"device_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
}

type Users struct {
	ID        int64              `json:"id"`
	StudentID string             `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Nickname  string             `json:"nickname"`
}

type WebSessionTickets struct {
	TicketHash   string             `json:"ticket_hash"`
	UserID       int64              `json:"user_id"`
	KeyID        int64              `json:"key_id"`
	RedirectPath string             `json:"redirect_path"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
