// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLabProfilesByLab = `-- name: ListLabProfilesByLab :many
SELECT user_id, lab_id, nickname, track
FROM lab_profiles
WHERE lab_id = $1
ORDER BY user_id
`

func (q *Queries) ListLabProfilesByLab(ctx context.Context, labID string) ([]LabProfiles, error) {
	rows, err := q.db.Query(ctx, listLabProfilesByLab, labID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LabProfiles{}
	for rows.Next() {
		var i LabProfiles
		if err := rows.Scan(
			&i.UserID,
			&i.LabID,
			&i.Nickname,
			&i.Track,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLabProfileNickname = `-- name: UpsertLabProfileNickname :one
INSERT INTO lab_profiles (user_id, lab_id, nickname)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, lab_id)
DO UPDATE SET nickname = EXCLUDED.nickname
RETURNING user_id, lab_id, nickname, track
`

type UpsertLabProfileNicknameParams struct {
	UserID   int64  `json:"user_id"`
	LabID    string `json:"lab_id"`
	Nickname string `json:"nickname"`
}

func (q *Queries) UpsertLabProfileNickname(ctx context.Context, arg UpsertLabProfileNicknameParams) (LabProfiles, error) {
	row := q.db.QueryRow(ctx, upsertLabProfileNickname, arg.UserID, arg.LabID, arg.Nickname)
	var i LabProfiles
	err := row.Scan(
		&i.UserID,
		&i.LabID,
		&i.Nickname,
		&i.Track,
	)
	return i, err
}

const upsertLabProfileTrack = `-- name: UpsertLabProfileTrack :one
INSERT INTO lab_profiles (user_id, lab_id, nickname, track)
VALUES ($1, $2, '匿名', $3)
ON CONFLICT (user_id, lab_id)
DO UPDATE SET track = EXCLUDED.track
RETURNING user_id, lab_id, nickname, track
`

type UpsertLabProfileTrackParams struct {
	UserID int64       `json:"user_id"`
	LabID  string      `json:"lab_id"`
	Track  pgtype.Text `json:"track"`
}

func (q *Queries) UpsertLabProfileTrack(ctx context.Context, arg UpsertLabProfileTrackParams) (LabProfiles, error) {
	row := q.db.QueryRow(ctx, upsertLabProfileTrack, arg.UserID, arg.LabID, arg.Track)
	var i LabProfiles
	err := row.Scan(
		&i.UserID,
		&i.LabID,
		&i.Nickname,
		&i.Track,
	)
	return i, err
}
