// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScore = `-- name: CreateScore :exec
INSERT INTO scores (submission_id, metric_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (submission_id, metric_id)
DO UPDATE SET value = EXCLUDED.value
`

type CreateScoreParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	MetricID     string    `json:"metric_id"`
	Value        float32   `json:"value"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) error {
	_, err := q.db.Exec(ctx, createScore, arg.SubmissionID, arg.MetricID, arg.Value)
	return err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    user_id, lab_id, key_id, artifact_key, content_hash, status,
    verdict, message, detail, image_digest, started_at, finished_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, lab_id, key_id, artifact_key, content_hash, status, verdict, message, detail, image_digest, started_at, finished_at, created_at
`

type CreateSubmissionParams struct {
	UserID      int64              `json:"user_id"`
	LabID       string             `json:"lab_id"`
	KeyID       int64              `json:"key_id"`
	ArtifactKey string             `json:"artifact_key"`
	ContentHash string             `json:"content_hash"`
	Status      string             `json:"status"`
	Verdict     pgtype.Text        `json:"verdict"`
	Message     pgtype.Text        `json:"message"`
	Detail      []byte             `json:"detail"`
	ImageDigest pgtype.Text        `json:"image_digest"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submissions, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.LabID,
		arg.KeyID,
		arg.ArtifactKey,
		arg.ContentHash,
		arg.Status,
		arg.Verdict,
		arg.Message,
		arg.Detail,
		arg.ImageDigest,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Submissions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.KeyID,
		&i.ArtifactKey,
		&i.ContentHash,
		&i.Status,
		&i.Verdict,
		&i.Message,
		&i.Detail,
		&i.ImageDigest,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestScoredSubmissionByUserLab = `-- name: GetLatestScoredSubmissionByUserLab :one
SELECT id, user_id, lab_id, key_id, artifact_key, content_hash, status, verdict, message, detail, image_digest, started_at, finished_at, created_at
FROM submissions
WHERE user_id = $1
  AND lab_id = $2
  AND verdict = 'scored'
ORDER BY finished_at DESC NULLS LAST, created_at DESC
LIMIT 1
`

type GetLatestScoredSubmissionByUserLabParams struct {
	UserID int64  `json:"user_id"`
	LabID  string `json:"lab_id"`
}

func (q *Queries) GetLatestScoredSubmissionByUserLab(ctx context.Context, arg GetLatestScoredSubmissionByUserLabParams) (Submissions, error) {
	row := q.db.QueryRow(ctx, getLatestScoredSubmissionByUserLab, arg.UserID, arg.LabID)
	var i Submissions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.KeyID,
		&i.ArtifactKey,
		&i.ContentHash,
		&i.Status,
		&i.Verdict,
		&i.Message,
		&i.Detail,
		&i.ImageDigest,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, user_id, lab_id, key_id, artifact_key, content_hash, status, verdict, message, detail, image_digest, started_at, finished_at, created_at
FROM submissions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submissions, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submissions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LabID,
		&i.KeyID,
		&i.ArtifactKey,
		&i.ContentHash,
		&i.Status,
		&i.Verdict,
		&i.Message,
		&i.Detail,
		&i.ImageDigest,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScoresBySubmission = `-- name: ListScoresBySubmission :many
SELECT submission_id, metric_id, value
FROM scores
WHERE submission_id = $1
ORDER BY metric_id
`

func (q *Queries) ListScoresBySubmission(ctx context.Context, submissionID uuid.UUID) ([]Scores, error) {
	rows, err := q.db.Query(ctx, listScoresBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scores{}
	for rows.Next() {
		var i Scores
		if err := rows.Scan(&i.SubmissionID, &i.MetricID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByUserLab = `-- name: ListSubmissionsByUserLab :many
SELECT id, user_id, lab_id, key_id, artifact_key, content_hash, status, verdict, message, detail, image_digest, started_at, finished_at, created_at
FROM submissions
WHERE user_id = $1 AND lab_id = $2
ORDER BY created_at DESC
`

type ListSubmissionsByUserLabParams struct {
	UserID int64  `json:"user_id"`
	LabID  string `json:"lab_id"`
}

func (q *Queries) ListSubmissionsByUserLab(ctx context.Context, arg ListSubmissionsByUserLabParams) ([]Submissions, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByUserLab, arg.UserID, arg.LabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submissions{}
	for rows.Next() {
		var i Submissions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LabID,
			&i.KeyID,
			&i.ArtifactKey,
			&i.ContentHash,
			&i.Status,
			&i.Verdict,
			&i.Message,
			&i.Detail,
			&i.ImageDigest,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionResult = `-- name: UpdateSubmissionResult :exec
UPDATE submissions
SET status = $2,
    verdict = $3,
    message = $4,
    detail = $5,
    image_digest = $6,
    started_at = $7,
    finished_at = $8
WHERE id = $1
`

type UpdateSubmissionResultParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	Verdict     pgtype.Text        `json:"verdict"`
	Message     pgtype.Text        `json:"message"`
	Detail      []byte             `json:"detail"`
	ImageDigest pgtype.Text        `json:"image_digest"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateSubmissionResult(ctx context.Context, arg UpdateSubmissionResultParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionResult,
		arg.ID,
		arg.Status,
		arg.Verdict,
		arg.Message,
		arg.Detail,
		arg.ImageDigest,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const updateSubmissionRunning = `-- name: UpdateSubmissionRunning :exec
UPDATE submissions
SET status = $2,
    started_at = $3
WHERE id = $1
`

type UpdateSubmissionRunningParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) UpdateSubmissionRunning(ctx context.Context, arg UpdateSubmissionRunningParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionRunning, arg.ID, arg.Status, arg.StartedAt)
	return err
}
