// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web_session_tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireWebSessionTicketCreateLock = `-- name: AcquireWebSessionTicketCreateLock :exec
SELECT pg_advisory_xact_lock(424242424242)
`

func (q *Queries) AcquireWebSessionTicketCreateLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireWebSessionTicketCreateLock)
	return err
}

const cleanupExpiredWebSessionTickets = `-- name: CleanupExpiredWebSessionTickets :exec
DELETE FROM web_session_tickets
WHERE expires_at <= NOW()
`

func (q *Queries) CleanupExpiredWebSessionTickets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredWebSessionTickets)
	return err
}

const consumeWebSessionTicket = `-- name: ConsumeWebSessionTicket :one
DELETE FROM web_session_tickets
WHERE ticket_hash = $1
  AND expires_at > NOW()
RETURNING ticket_hash, user_id, key_id, redirect_path, expires_at, created_at
`

func (q *Queries) ConsumeWebSessionTicket(ctx context.Context, ticketHash string) (WebSessionTickets, error) {
	row := q.db.QueryRow(ctx, consumeWebSessionTicket, ticketHash)
	var i WebSessionTickets
	err := row.Scan(
		&i.TicketHash,
		&i.UserID,
		&i.KeyID,
		&i.RedirectPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveWebSessionTickets = `-- name: CountActiveWebSessionTickets :one
SELECT count(*)::bigint
FROM web_session_tickets
WHERE expires_at > NOW()
`

func (q *Queries) CountActiveWebSessionTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWebSessionTickets)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWebSessionTicket = `-- name: CreateWebSessionTicket :one
INSERT INTO web_session_tickets (ticket_hash, user_id, key_id, redirect_path, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING ticket_hash, user_id, key_id, redirect_path, expires_at, created_at
`

type CreateWebSessionTicketParams struct {
	TicketHash   string             `json:"ticket_hash"`
	UserID       int64              `json:"user_id"`
	KeyID        int64              `json:"key_id"`
	RedirectPath string             `json:"redirect_path"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWebSessionTicket(ctx context.Context, arg CreateWebSessionTicketParams) (WebSessionTickets, error) {
	row := q.db.QueryRow(ctx, createWebSessionTicket,
		arg.TicketHash,
		arg.UserID,
		arg.KeyID,
		arg.RedirectPath,
		arg.ExpiresAt,
	)
	var i WebSessionTickets
	err := row.Scan(
		&i.TicketHash,
		&i.UserID,
		&i.KeyID,
		&i.RedirectPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
